name = "project doc"
license = "MIT"
licenselink = "https://github.com/lrntct/hugo-project-doc/blob/master/LICENSE.md"
description = "A theme for software project websites."
homepage = "https://github.com/lrntct/hugo-project-doc"
tags = ["documentation", "projects", "font awesome", "company", "responsive", "blog"]
features = ["google analytics", "search"]
min_version = 0.22

[author]
  name = "Laurent Courty"
  homepage = "http://www.courty.me"

# If porting an existing theme
[original]
  name = "jekyll-doc-theme"
  homepage = "https://github.com/aksakalli/"
  repo = "https://github.com/aksakalli/jekyll-doc-theme"
